In [2]:
#Dependencies
import pandas as pd
from sqlalchemy import create_engine
import numpy as np
import psycopg2

In [3]:
poki520_csv = 'data/pokedex_0520.csv'
pokimain_df = pd.read_csv(poki520_csv, encoding='UTF-8')
pokimain_df.head()

,Unnamed: 0,pokedex_number,name,german_name,japanese_name,generation,status,species,type_number,type_1,...,against_ground,against_flying,against_psychic,against_bug,against_rock,against_ghost,against_dragon,against_dark,against_steel,against_fairy
0,0,1,Bulbasaur,Bisasam,フシギダネ (Fushigidane),1,Normal,Seed Pokémon,2,Grass,...,1.0,2.0,2.0,1.0,1.0,1.0,1.0,1.0,1.0,0.5
1,1,2,Ivysaur,Bisaknosp,フシギソウ (Fushigisou),1,Normal,Seed Pokémon,2,Grass,...,1.0,2.0,2.0,1.0,1.0,1.0,1.0,1.0,1.0,0.5
2,2,3,Venusaur,Bisaflor,フシギバナ (Fushigibana),1,Normal,Seed Pokémon,2,Grass,...,1.0,2.0,2.0,1.0,1.0,1.0,1.0,1.0,1.0,0.5
3,3,3,Mega Venusaur,Bisaflor,フシギバナ (Fushigibana),1,Normal,Seed Pokémon,2,Grass,...,1.0,2.0,2.0,1.0,1.0,1.0,1.0,1.0,1.0,0.5
4,4,4,Charmander,Glumanda,ヒトカゲ (Hitokage),1,Normal,Lizard Pokémon,1,Fire,...,2.0,1.0,1.0,0.5,2.0,1.0,1.0,1.0,0.5,0.5

In [4]:
poki420_csv = 'data/pokedex_0420.csv'
pokilegends_df = pd.read_csv(poki420_csv, encoding='UTF-8')
pokilegends_df.head()

,Unnamed: 0,pokedex_number,name,german_name,japanese_name,generation,is_sub_legendary,is_legendary,is_mythical,species,...,against_ground,against_flying,against_psychic,against_bug,against_rock,against_ghost,against_dragon,against_dark,against_steel,against_fairy
0,0,1,Bulbasaur,Bisasam,フシギダネ (Fushigidane),1,0,0,0,Seed Pokémon,...,1.0,2.0,2.0,1.0,1.0,1.0,1.0,1.0,1.0,0.5
1,1,2,Ivysaur,Bisaknosp,フシギソウ (Fushigisou),1,0,0,0,Seed Pokémon,...,1.0,2.0,2.0,1.0,1.0,1.0,1.0,1.0,1.0,0.5
2,2,3,Venusaur,Bisaflor,フシギバナ (Fushigibana),1,0,0,0,Seed Pokémon,...,1.0,2.0,2.0,1.0,1.0,1.0,1.0,1.0,1.0,0.5
3,3,3,Mega Venusaur,Bisaflor,フシギバナ (Fushigibana),1,0,0,0,Seed Pokémon,...,1.0,2.0,2.0,1.0,1.0,1.0,1.0,1.0,1.0,0.5
4,4,4,Charmander,Glumanda,ヒトカゲ (Hitokage),1,0,0,0,Lizard Pokémon,...,2.0,1.0,1.0,0.5,2.0,1.0,1.0,1.0,0.5,0.5

In [5]:
# Listing all columns in main DF  
pokimain_df.columns

Index(['Unnamed: 0', 'pokedex_number', 'name', 'german_name', 'japanese_name',
       'generation', 'status', 'species', 'type_number', 'type_1', 'type_2',
       'height_m', 'weight_kg', 'abilities_number', 'ability_1', 'ability_2',
       'ability_hidden', 'total_points', 'hp', 'attack', 'defense',
       'sp_attack', 'sp_defense', 'speed', 'catch_rate', 'base_friendship',
       'base_experience', 'growth_rate', 'egg_type_number', 'egg_type_1',
       'egg_type_2', 'percentage_male', 'egg_cycles', 'against_normal',
       'against_fire', 'against_water', 'against_electric', 'against_grass',
       'against_ice', 'against_fight', 'against_poison', 'against_ground',
       'against_flying', 'against_psychic', 'against_bug', 'against_rock',
       'against_ghost', 'against_dragon', 'against_dark', 'against_steel',
       'against_fairy'],
      dtype='object')

In [6]:
# Listing all columns in main DF  
pokilegends_df.columns

Index(['Unnamed: 0', 'pokedex_number', 'name', 'german_name', 'japanese_name',
       'generation', 'is_sub_legendary', 'is_legendary', 'is_mythical',
       'species', 'type_number', 'type_1', 'type_2', 'height_m', 'weight_kg',
       'abilities_number', 'ability_1', 'ability_2', 'ability_hidden',
       'total_points', 'hp', 'attack', 'defense', 'sp_attack', 'sp_defense',
       'speed', 'catch_rate', 'base_friendship', 'base_experience',
       'growth_rate', 'egg_type_number', 'egg_type_1', 'egg_type_2',
       'percentage_male', 'egg_cycles', 'against_normal', 'against_fire',
       'against_water', 'against_electric', 'against_grass', 'against_ice',
       'against_fight', 'against_poison', 'against_ground', 'against_flying',
       'against_psychic', 'against_bug', 'against_rock', 'against_ghost',
       'against_dragon', 'against_dark', 'against_steel', 'against_fairy'],
      dtype='object')

In [7]:
legendary_df = pokilegends_df[["pokedex_number", "name","is_sub_legendary", "is_legendary", "is_mythical", 'total_points', 'hp', 'attack', 'defense', 'sp_attack', 'sp_defense', 'speed']]
legendary_df.head()

,pokedex_number,name,is_sub_legendary,is_legendary,is_mythical,total_points,hp,attack,defense,sp_attack,sp_defense,speed
0,1,Bulbasaur,0,0,0,318.0,45.0,49.0,49.0,65.0,65.0,45.0
1,2,Ivysaur,0,0,0,405.0,60.0,62.0,63.0,80.0,80.0,60.0
2,3,Venusaur,0,0,0,525.0,80.0,82.0,83.0,100.0,100.0,80.0
3,3,Mega Venusaur,0,0,0,625.0,80.0,100.0,123.0,122.0,120.0,80.0
4,4,Charmander,0,0,0,309.0,39.0,52.0,43.0,60.0,50.0,65.0

In [8]:
pd.set_option('display.max_rows', None) 
legendary_cleandf = legendary_df.loc[(((legendary_df['is_sub_legendary'] != 0) | (legendary_df['is_legendary'] != 0) | (legendary_df['is_mythical'] != 0)))].dropna(how='all', axis=0)
legendary_cleandf

,pokedex_number,name,is_sub_legendary,is_legendary,is_mythical,total_points,hp,attack,defense,sp_attack,sp_defense,speed
182,144,Articuno,1,0,0,580.0,90.0,85.0,100.0,95.0,125.0,85.0
183,145,Zapdos,1,0,0,580.0,90.0,90.0,85.0,125.0,90.0,100.0
184,146,Moltres,1,0,0,580.0,90.0,100.0,90.0,125.0,85.0,90.0
188,150,Mewtwo,0,1,0,680.0,106.0,110.0,90.0,154.0,90.0,130.0
189,150,Mega Mewtwo X,0,1,0,780.0,106.0,190.0,100.0,154.0,100.0,130.0
190,150,Mega Mewtwo Y,0,1,0,780.0,106.0,150.0,70.0,194.0,120.0,140.0
191,151,Mew,0,0,1,600.0,100.0,100.0,100.0,100.0,100.0,100.0
289,243,Raikou,1,0,0,580.0,90.0,85.0,75.0,115.0,100.0,115.0
290,244,Entei,1,0,0,580.0,115.0,115.0,85.0,90.0,75.0,100.0
291,245,Suicune,1,0,0,580.0,100.0,75.0,115.0,90.0,115.0,85.0
296,249,Lugia,0,1,0,680.0,106.0,90.0,130.0,90.0,154.0,110.0
297,250,Ho-oh,0,1,0,680.0,106.0,130.0,90.0,110.0,154.0,90.0
298,251,Celebi,0,0,1,600.0,100.0,100.0,100.0,100.0,100.0,100.0
446,377,Regirock,1,0,0,580.0,80.0,100.0,200.0,50.0,100.0,50.0
447,378,Regice,1,0,0,580.0,80.0,50.0,100.0,100.0,200.0,50.0
448,379,Registeel,1,0,0,580.0,80.0,75.0,150.0,75.0,150.0,50.0
449,380,Latias,1,0,0,600.0,80.0,80.0,90.0,110.0,130.0,110.0
450,380,Mega Latias,1,0,0,700.0,80.0,100.0,120.0,140.0,150.0,110.0
451,381,Latios,1,0,0,600.0,80.0,90.0,80.0,130.0,110.0,110.0
452,381,Mega Latios,1,0,0,700.0,80.0,130.0,100.0,160.0,120.0,110.0
453,382,Kyogre,0,1,0,670.0,100.0,100.0,90.0,150.0,140.0,90.0
454,382,Primal Kyogre,0,1,0,770.0,100.0,150.0,90.0,180.0,160.0,90.0
455,383,Groudon,0,1,0,670.0,100.0,150.0,140.0,100.0,90.0,90.0
456,383,Primal Groudon,0,1,0,770.0,100.0,180.0,160.0,150.0,90.0,90.0
457,384,Rayquaza,0,1,0,680.0,105.0,150.0,90.0,150.0,90.0,95.0
458,384,Mega Rayquaza,0,1,0,780.0,105.0,180.0,100.0,180.0,100.0,115.0
459,385,Jirachi,0,0,1,600.0,100.0,100.0,100.0,100.0,100.0,100.0
460,386,Deoxys Normal Forme,0,0,1,600.0,50.0,150.0,50.0,150.0,50.0,150.0
461,386,Deoxys Attack Forme,0,0,1,600.0,50.0,180.0,20.0,180.0,20.0,150.0
462,386,Deoxys Defense Forme,0,0,1,600.0,50.0,70.0,160.0,70.0,160.0,90.0
463,386,Deoxys Speed Forme,0,0,1,600.0,50.0,95.0,90.0,95.0,90.0,180.0
569,480,Uxie,1,0,0,580.0,75.0,75.0,130.0,75.0,130.0,95.0
570,481,Mesprit,1,0,0,580.0,80.0,105.0,105.0,105.0,105.0,80.0
571,482,Azelf,1,0,0,580.0,75.0,125.0,70.0,125.0,70.0,115.0
572,483,Dialga,0,1,0,680.0,100.0,120.0,120.0,150.0,100.0,90.0
573,484,Palkia,0,1,0,680.0,90.0,120.0,100.0,150.0,120.0,100.0
574,485,Heatran,1,0,0,600.0,91.0,90.0,106.0,130.0,106.0,77.0
575,486,Regigigas,1,0,0,670.0,110.0,160.0,110.0,80.0,110.0,100.0
576,487,Giratina Altered Forme,0,1,0,680.0,150.0,100.0,120.0,100.0,120.0,90.0
577,487,Giratina Origin Forme,0,1,0,680.0,150.0,120.0,100.0,120.0,100.0,90.0
578,488,Cresselia,1,0,0,600.0,120.0,70.0,120.0,75.0,130.0,85.0
579,489,Phione,0,0,1,480.0,80.0,80.0,80.0,80.0,80.0,80.0
580,490,Manaphy,0,0,1,600.0,100.0,100.0,100.0,100.0,100.0,100.0
581,491,Darkrai,0,0,1,600.0,70.0,90.0,90.0,135.0,90.0,125.0
582,492,Shaymin Land Forme,0,0,1,600.0,100.0,100.0,100.0,100.0,100.0,100.0
583,492,Shaymin Sky Forme,0,0,1,600.0,100.0,103.0,75.0,120.0,75.0,127.0
584,493,Arceus,0,0,1,720.0,120.0,120.0,120.0,120.0,120.0,120.0
585,494,Victini,0,0,1,600.0,100.0,100.0,100.0,100.0,100.0,100.0
737,638,Cobalion,1,0,0,580.0,91.0,90.0,129.0,90.0,72.0,108.0
738,639,Terrakion,1,0,0,580.0,91.0,129.0,90.0,72.0,90.0,108.0
739,640,Virizion,1,0,0,580.0,91.0,90.0,72.0,90.0,129.0,108.0
740,641,Tornadus Incarnate Forme,1,0,0,580.0,79.0,115.0,70.0,125.0,80.0,111.0
741,641,Tornadus Therian Forme,1,0,0,580.0,79.0,100.0,80.0,110.0,90.0,121.0
742,642,Thundurus Incarnate Forme,1,0,0,580.0,79.0,115.0,70.0,125.0,80.0,111.0
743,642,Thundurus Therian Forme,1,0,0,580.0,79.0,105.0,70.0,145.0,80.0,101.0
744,643,Reshiram,0,1,0,680.0,100.0,120.0,100.0,150.0,120.0,90.0
745,644,Zekrom,0,1,0,680.0,100.0,150.0,120.0,120.0,100.0,90.0
746,645,Landorus Incarnate Forme,1,0,0,600.0,89.0,125.0,90.0,115.0,80.0,101.0
747,645,Landorus Therian Forme,1,0,0,600.0,89.0,145.0,90.0,105.0,80.0,91.0
748,646,Kyurem,0,1,0,660.0,125.0,130.0,90.0,130.0,90.0,95.0
749,646,Black Kyurem,0,1,0,700.0,125.0,170.0,100.0,120.0,90.0,95.0
750,646,White Kyurem,0,1,0,700.0,125.0,120.0,90.0,170.0,100.0,95.0
751,647,Keldeo Ordinary Forme,0,0,1,580.0,91.0,72.0,90.0,129.0,90.0,108.0
752,647,Keldeo Resolute Forme,0,0,1,580.0,91.0,72.0,90.0,129.0,90.0,108.0
753,648,Meloetta Aria Forme,0,0,1,600.0,100.0,77.0,77.0,128.0,128.0,90.0
754,648,Meloetta Pirouette Forme,0,0,1,600.0,100.0,128.0,90.0,77.0,77.0,128.0
755,649,Genesect,0,0,1,600.0,71.0,120.0,95.0,120.0,95.0,99.0
831,716,Xerneas,0,1,0,680.0,126.0,131.0,95.0,131.0,98.0,99.0
832,717,Yveltal,0,1,0,680.0,126.0,131.0,95.0,131.0,98.0,99.0
833,718,Zygarde 50% Forme,0,1,0,600.0,108.0,100.0,121.0,81.0,95.0,95.0
834,718,Zygarde 10% Forme,0,1,0,486.0,54.0,100.0,71.0,61.0,85.0,115.0
835,718,Zygarde Complete Forme,0,1,0,708.0,216.0,100.0,121.0,91.0,95.0,85.0
836,719,Diancie,0,0,1,600.0,50.0,100.0,150.0,100.0,150.0,50.0
837,719,Mega Diancie,0,0,1,700.0,50.0,160.0,110.0,160.0,110.0,110.0
838,720,Hoopa Hoopa Confined,0,0,1,600.0,80.0,110.0,60.0,150.0,130.0,70.0
839,720,Hoopa Hoopa Unbound,0,0,1,680.0,80.0,160.0,60.0,170.0,130.0,80.0
840,721,Volcanion,0,0,1,600.0,80.0,110.0,120.0,130.0,90.0,70.0
898,772,Type: Null,1,0,0,534.0,95.0,95.0,95.0,95.0,95.0,59.0
899,773,Silvally,1,0,0,570.0,95.0,95.0,95.0,95.0,95.0,95.0
912,785,Tapu Koko,1,0,0,570.0,70.0,115.0,85.0,95.0,75.0,130.0
913,786,Tapu Lele,1,0,0,570.0,70.0,85.0,75.0,130.0,115.0,95.0
914,787,Tapu Bulu,1,0,0,570.0,70.0,130.0,115.0,85.0,95.0,75.0
915,788,Tapu Fini,1,0,0,570.0,70.0,75.0,115.0,95.0,130.0,85.0
916,789,Cosmog,0,1,0,200.0,43.0,29.0,31.0,29.0,31.0,37.0
917,790,Cosmoem,0,1,0,400.0,43.0,29.0,131.0,29.0,131.0,37.0
918,791,Solgaleo,0,1,0,680.0,137.0,137.0,107.0,113.0,89.0,97.0
919,792,Lunala,0,1,0,680.0,137.0,113.0,89.0,137.0,107.0,97.0
920,793,Nihilego,1,0,0,570.0,109.0,53.0,47.0,127.0,131.0,103.0
921,794,Buzzwole,1,0,0,570.0,107.0,139.0,139.0,53.0,53.0,79.0
922,795,Pheromosa,1,0,0,570.0,71.0,137.0,37.0,137.0,37.0,151.0
923,796,Xurkitree,1,0,0,570.0,83.0,89.0,71.0,173.0,71.0,83.0
924,797,Celesteela,1,0,0,570.0,97.0,101.0,103.0,107.0,101.0,61.0
925,798,Kartana,1,0,0,570.0,59.0,181.0,131.0,59.0,31.0,109.0
926,799,Guzzlord,1,0,0,570.0,223.0,101.0,53.0,97.0,53.0,43.0
927,800,Necrozma,0,1,0,600.0,97.0,107.0,101.0,127.0,89.0,79.0
928,800,Dusk Mane Necrozma,0,1,0,680.0,97.0,157.0,127.0,113.0,109.0,77.0
929,800,Dawn Wings Necrozma,0,1,0,680.0,97.0,113.0,109.0,157.0,127.0,77.0
930,800,Ultra Necrozma,0,1,0,754.0,97.0,167.0,97.0,167.0,97.0,129.0
931,801,Magearna,0,0,1,600.0,80.0,95.0,115.0,130.0,115.0,65.0
932,802,Marshadow,0,0,1,600.0,90.0,125.0,80.0,90.0,90.0,125.0
933,803,Poipole,1,0,0,420.0,67.0,73.0,67.0,73.0,67.0,73.0
934,804,Naganadel,1,0,0,540.0,73.0,73.0,73.0,127.0,73.0,121.0
935,805,Stakataka,1,0,0,570.0,61.0,131.0,211.0,53.0,101.0,13.0
936,806,Blacephalon,1,0,0,570.0,53.0,127.0,53.0,151.0,79.0,107.0
937,807,Zeraora,0,0,1,600.0,88.0,112.0,75.0,102.0,80.0,143.0
938,808,Meltan,0,0,1,300.0,46.0,65.0,65.0,55.0,35.0,34.0
939,809,Melmetal,0,0,1,600.0,135.0,143.0,143.0,80.0,65.0,34.0
1022,888,Zacian Crowned Sword,0,1,0,720.0,92.0,170.0,115.0,80.0,115.0,148.0
1023,888,Zacian Hero of Many Battles,0,1,0,670.0,92.0,130.0,115.0,80.0,115.0,138.0
1024,889,Zamazenta Crowned Shield,0,1,0,720.0,92.0,130.0,145.0,80.0,145.0,128.0
1025,889,Zamazenta Hero of Many Battles,0,1,0,670.0,92.0,130.0,115.0,80.0,115.0,138.0
1026,890,Eternatus,0,1,0,690.0,140.0,85.0,95.0,145.0,95.0,130.0
1027,890,Eternatus Eternamax,0,1,0,1125.0,255.0,115.0,250.0,125.0,250.0,130.0

In [9]:
starters = ["Bulbasaur", "Ivysaur", "Venusaur", "Charmander", "Charmeleon", "Charizard", "Squirtle", 'Wartortle', 'Blastoise',
'Chikorita', "Bayleef", "Meganium", "Cyndaquil", "Quilava", "Typhlosion", "Totodile", 'Croconaw', 'Feraligatr',
"Treecko", 'Grovyle', 'Sceptile', "Torchic", "Combusken", "Blaziken", "Mudkip", "Marshtomp", 'Swampert',
"Turtwig", "Grotle", "Torterra", 'Chimchar', 'Monferno', "Infernape", "Piplup", "Prinplup", "Empoleon",
"Snivy", 'Servine', "Serperior", "Tepig", 'Pignite', "Emboar", "Oshawott", "Dewott", "Samurott",
'Chespin', "Quilladin", 'Chesnaught', "Fennekin", "Braixen", "Delphox", 'Froakie', 'Frogadier', "Greninja",
"Rowlet", 'Dartrix', "Decidueye", "Litten", "Torracat", "Incineroar", "Popplio", 'Brionne', "Primarina", 
"Grookey", 'Thwackey', "Rillaboom", "Scorbunny", "Raboot", "Cinderace", "Sobble", "Drizzile", "Inteleon"]

In [10]:
for pokemon in pokimain_df["name"]:
    starter_index = pokimain_df[pokimain_df["name"] == pokemon].index
    if pokemon in starters:
        pokimain_df.loc[starter_index, "is_starter"] = 1
    else: 
        pokimain_df.loc[starter_index, "is_starter"] = 0

In [11]:
pokimain_df.head()

,Unnamed: 0,pokedex_number,name,german_name,japanese_name,generation,status,species,type_number,type_1,...,against_flying,against_psychic,against_bug,against_rock,against_ghost,against_dragon,against_dark,against_steel,against_fairy,is_starter
0,0,1,Bulbasaur,Bisasam,フシギダネ (Fushigidane),1,Normal,Seed Pokémon,2,Grass,...,2.0,2.0,1.0,1.0,1.0,1.0,1.0,1.0,0.5,1.0
1,1,2,Ivysaur,Bisaknosp,フシギソウ (Fushigisou),1,Normal,Seed Pokémon,2,Grass,...,2.0,2.0,1.0,1.0,1.0,1.0,1.0,1.0,0.5,1.0
2,2,3,Venusaur,Bisaflor,フシギバナ (Fushigibana),1,Normal,Seed Pokémon,2,Grass,...,2.0,2.0,1.0,1.0,1.0,1.0,1.0,1.0,0.5,1.0
3,3,3,Mega Venusaur,Bisaflor,フシギバナ (Fushigibana),1,Normal,Seed Pokémon,2,Grass,...,2.0,2.0,1.0,1.0,1.0,1.0,1.0,1.0,0.5,0.0
4,4,4,Charmander,Glumanda,ヒトカゲ (Hitokage),1,Normal,Lizard Pokémon,1,Fire,...,1.0,1.0,0.5,2.0,1.0,1.0,1.0,0.5,0.5,1.0

In [12]:
starter_cleandf = pokimain_df[["pokedex_number", "name", "generation", "is_starter",'total_points', 'hp', 'attack', 'defense', 'sp_attack', 'sp_defense', 'speed']]
starter_cleandf = starter_cleandf.loc[(starter_cleandf['is_starter'] != 0)]
starter_cleandf

,pokedex_number,name,generation,is_starter,total_points,hp,attack,defense,sp_attack,sp_defense,speed
0,1,Bulbasaur,1,1.0,318,45,49,49,65,65,45
1,2,Ivysaur,1,1.0,405,60,62,63,80,80,60
2,3,Venusaur,1,1.0,525,80,82,83,100,100,80
4,4,Charmander,1,1.0,309,39,52,43,60,50,65
5,5,Charmeleon,1,1.0,405,58,64,58,80,65,80
6,6,Charizard,1,1.0,534,78,84,78,109,85,100
9,7,Squirtle,1,1.0,314,44,48,65,50,64,43
10,8,Wartortle,1,1.0,405,59,63,80,65,80,58
11,9,Blastoise,1,1.0,530,79,83,100,85,105,78
192,152,Chikorita,2,1.0,318,45,49,65,49,65,45
193,153,Bayleef,2,1.0,405,60,62,80,63,80,60
194,154,Meganium,2,1.0,525,80,82,100,83,100,80
195,155,Cyndaquil,2,1.0,309,39,52,43,60,50,65
196,156,Quilava,2,1.0,405,58,64,58,80,65,80
197,157,Typhlosion,2,1.0,534,78,84,78,109,85,100
198,158,Totodile,2,1.0,314,50,65,64,44,48,43
199,159,Croconaw,2,1.0,405,65,80,80,59,63,58
200,160,Feraligatr,2,1.0,530,85,105,100,79,83,78
299,252,Treecko,3,1.0,310,40,45,35,65,55,70
300,253,Grovyle,3,1.0,405,50,65,45,85,65,95
301,254,Sceptile,3,1.0,530,70,85,65,105,85,120
303,255,Torchic,3,1.0,310,45,60,40,70,50,45
304,256,Combusken,3,1.0,405,60,85,60,85,60,55
305,257,Blaziken,3,1.0,530,80,120,70,110,70,80
307,258,Mudkip,3,1.0,310,50,70,50,50,50,40
308,259,Marshtomp,3,1.0,405,70,85,70,60,70,50
309,260,Swampert,3,1.0,535,100,110,90,85,90,60
464,387,Turtwig,4,1.0,318,55,68,64,45,55,31
465,388,Grotle,4,1.0,405,75,89,85,55,65,36
466,389,Torterra,4,1.0,525,95,109,105,75,85,56
467,390,Chimchar,4,1.0,309,44,58,44,58,44,61
468,391,Monferno,4,1.0,405,64,78,52,78,52,81
469,392,Infernape,4,1.0,534,76,104,71,104,71,108
470,393,Piplup,4,1.0,314,53,51,53,61,56,40
471,394,Prinplup,4,1.0,405,64,66,68,81,76,50
472,395,Empoleon,4,1.0,530,84,86,88,111,101,60
586,495,Snivy,5,1.0,308,45,45,55,45,55,63
587,496,Servine,5,1.0,413,60,60,75,60,75,83
588,497,Serperior,5,1.0,528,75,75,95,75,95,113
589,498,Tepig,5,1.0,308,65,63,45,45,45,45
590,499,Pignite,5,1.0,418,90,93,55,70,55,55
591,500,Emboar,5,1.0,528,110,123,65,100,65,65
592,501,Oshawott,5,1.0,308,55,55,45,63,45,45
593,502,Dewott,5,1.0,413,75,75,60,83,60,60
594,503,Samurott,5,1.0,528,95,100,85,108,70,70
756,650,Chespin,6,1.0,313,56,61,65,48,45,38
757,651,Quilladin,6,1.0,405,61,78,95,56,58,57
758,652,Chesnaught,6,1.0,530,88,107,122,74,75,64
759,653,Fennekin,6,1.0,307,40,45,40,62,60,60
760,654,Braixen,6,1.0,409,59,59,58,90,70,73
761,655,Delphox,6,1.0,534,75,69,72,114,100,104
762,656,Froakie,6,1.0,314,41,56,40,62,44,71
763,657,Frogadier,6,1.0,405,54,63,52,83,56,97
764,658,Greninja,6,1.0,530,72,95,67,103,71,122
841,722,Rowlet,7,1.0,320,68,55,55,50,50,42
842,723,Dartrix,7,1.0,420,78,75,75,70,70,52
843,724,Decidueye,7,1.0,530,78,107,75,100,100,70
844,725,Litten,7,1.0,320,45,65,40,60,40,70
845,726,Torracat,7,1.0,420,65,85,50,80,50,90
846,727,Incineroar,7,1.0,530,95,115,90,80,90,60
847,728,Popplio,7,1.0,320,50,54,54,66,56,40
848,729,Brionne,7,1.0,420,60,69,69,91,81,50
849,730,Primarina,7,1.0,530,80,74,74,126,116,60
940,810,Grookey,8,1.0,310,50,65,50,40,40,65
941,811,Thwackey,8,1.0,420,70,85,70,55,60,80
942,812,Rillaboom,8,1.0,530,100,125,90,60,70,85
943,813,Scorbunny,8,1.0,310,50,71,40,40,40,69
944,814,Raboot,8,1.0,420,65,86,60,55,60,94
945,815,Cinderace,8,1.0,530,80,116,75,65,75,119
946,816,Sobble,8,1.0,310,50,40,40,70,40,70
947,817,Drizzile,8,1.0,420,65,60,55,95,55,90
948,818,Inteleon,8,1.0,530,70,85,65,125,65,120

In [13]:
pokimain_df = pokimain_df[['pokedex_number', 'name',
       'generation', 'status', 'species', 'type_number', 'type_1', 'type_2',
       'height_m', 'weight_kg', 'abilities_number', 'ability_1', 'ability_2',
       'ability_hidden', 'total_points', 'hp', 'attack', 'defense',
       'sp_attack', 'sp_defense', 'speed', 'catch_rate', 'base_friendship',
       'base_experience', 'growth_rate', 'egg_type_number', 'egg_type_1',
       'egg_type_2', 'percentage_male', 'egg_cycles', 'against_normal',
       'against_fire', 'against_water', 'against_electric', 'against_grass',
       'against_ice', 'against_fight', 'against_poison', 'against_ground',
       'against_flying', 'against_psychic', 'against_bug', 'against_rock',
       'against_ghost', 'against_dragon', 'against_dark', 'against_steel',
       'against_fairy', "is_starter"]]
pokimain_df.head()

,pokedex_number,name,generation,status,species,type_number,type_1,type_2,height_m,weight_kg,...,against_flying,against_psychic,against_bug,against_rock,against_ghost,against_dragon,against_dark,against_steel,against_fairy,is_starter
0,1,Bulbasaur,1,Normal,Seed Pokémon,2,Grass,Poison,0.7,6.9,...,2.0,2.0,1.0,1.0,1.0,1.0,1.0,1.0,0.5,1.0
1,2,Ivysaur,1,Normal,Seed Pokémon,2,Grass,Poison,1.0,13.0,...,2.0,2.0,1.0,1.0,1.0,1.0,1.0,1.0,0.5,1.0
2,3,Venusaur,1,Normal,Seed Pokémon,2,Grass,Poison,2.0,100.0,...,2.0,2.0,1.0,1.0,1.0,1.0,1.0,1.0,0.5,1.0
3,3,Mega Venusaur,1,Normal,Seed Pokémon,2,Grass,Poison,2.4,155.5,...,2.0,2.0,1.0,1.0,1.0,1.0,1.0,1.0,0.5,0.0
4,4,Charmander,1,Normal,Lizard Pokémon,1,Fire,NaN,0.6,8.5,...,1.0,1.0,0.5,2.0,1.0,1.0,1.0,0.5,0.5,1.0

In [14]:
type_df = pokimain_df[["type_1","type_2",'against_normal',
       'against_fire', 'against_water', 'against_electric', 'against_grass',
       'against_ice', 'against_fight', 'against_poison', 'against_ground',
       'against_flying', 'against_psychic', 'against_bug', 'against_rock',
       'against_ghost', 'against_dragon', 'against_dark', 'against_steel',
       'against_fairy']]
type_df.head()

,type_1,type_2,against_normal,against_fire,against_water,against_electric,against_grass,against_ice,against_fight,against_poison,against_ground,against_flying,against_psychic,against_bug,against_rock,against_ghost,against_dragon,against_dark,against_steel,against_fairy
0,Grass,Poison,1.0,2.0,0.5,0.5,0.25,2.0,0.5,1.0,1.0,2.0,2.0,1.0,1.0,1.0,1.0,1.0,1.0,0.5
1,Grass,Poison,1.0,2.0,0.5,0.5,0.25,2.0,0.5,1.0,1.0,2.0,2.0,1.0,1.0,1.0,1.0,1.0,1.0,0.5
2,Grass,Poison,1.0,2.0,0.5,0.5,0.25,2.0,0.5,1.0,1.0,2.0,2.0,1.0,1.0,1.0,1.0,1.0,1.0,0.5
3,Grass,Poison,1.0,1.0,0.5,0.5,0.25,1.0,0.5,1.0,1.0,2.0,2.0,1.0,1.0,1.0,1.0,1.0,1.0,0.5
4,Fire,NaN,1.0,0.5,2.0,1.0,0.50,0.5,1.0,1.0,2.0,1.0,1.0,0.5,2.0,1.0,1.0,1.0,0.5,0.5

In [15]:
effectiveness_df = type_df[type_df['type_2'].isnull()]
effectiveness_df = effectiveness_df.drop_duplicates(subset=['type_1'])
effectiveness_df = effectiveness_df[["type_1",'against_normal',
       'against_fire', 'against_water', 'against_electric', 'against_grass',
       'against_ice', 'against_fight', 'against_poison', 'against_ground',
       'against_flying', 'against_psychic', 'against_bug', 'against_rock',
       'against_ghost', 'against_dragon', 'against_dark', 'against_steel',
       'against_fairy']]
effectiveness_df

,type_1,against_normal,against_fire,against_water,against_electric,against_grass,against_ice,against_fight,against_poison,against_ground,against_flying,against_psychic,against_bug,against_rock,against_ghost,against_dragon,against_dark,against_steel,against_fairy
4,Fire,1.0,0.5,2.0,1.0,0.5,0.5,1.0,1.0,2.0,1.0,1.0,0.5,2.0,1.0,1.0,1.0,0.5,0.5
9,Water,1.0,0.5,0.5,2.0,2.0,0.5,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,0.5,1.0
13,Bug,1.0,2.0,1.0,1.0,0.5,1.0,0.5,1.0,0.5,2.0,1.0,1.0,2.0,1.0,1.0,1.0,1.0,1.0
24,Normal,1.0,1.0,1.0,1.0,1.0,1.0,2.0,1.0,1.0,1.0,1.0,1.0,1.0,0.0,1.0,1.0,1.0,1.0
30,Poison,1.0,1.0,1.0,1.0,0.5,1.0,0.5,0.5,2.0,1.0,2.0,0.5,1.0,1.0,1.0,1.0,1.0,0.5
32,Electric,1.0,1.0,1.0,0.5,1.0,1.0,1.0,1.0,2.0,0.5,1.0,1.0,1.0,1.0,1.0,1.0,0.5,1.0
36,Ground,1.0,1.0,2.0,0.0,2.0,2.0,1.0,0.5,1.0,1.0,1.0,1.0,0.5,1.0,1.0,1.0,1.0,1.0
46,Fairy,1.0,1.0,1.0,1.0,1.0,1.0,0.5,2.0,1.0,1.0,1.0,0.5,1.0,1.0,0.0,0.5,2.0,1.0
49,Ice,1.0,0.5,2.0,1.0,0.5,0.5,1.0,1.0,2.0,1.0,1.0,0.5,2.0,1.0,1.0,1.0,0.5,0.5
68,Dark,1.0,1.0,1.0,1.0,1.0,1.0,2.0,1.0,1.0,1.0,0.0,2.0,1.0,0.5,1.0,0.5,1.0,2.0
69,Steel,0.5,2.0,1.0,1.0,0.5,0.5,2.0,0.0,2.0,0.5,0.5,0.5,0.5,1.0,0.5,1.0,0.5,0.5
74,Fighting,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,2.0,2.0,0.5,0.5,1.0,1.0,0.5,1.0,2.0
81,Psychic,1.0,1.0,1.0,1.0,1.0,1.0,0.5,1.0,1.0,1.0,0.5,2.0,1.0,2.0,1.0,2.0,1.0,1.0
146,Grass,1.0,2.0,0.5,0.5,0.5,2.0,1.0,2.0,0.5,2.0,1.0,2.0,1.0,1.0,1.0,1.0,1.0,1.0
185,Dragon,1.0,0.5,0.5,0.5,0.5,2.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,2.0,1.0,1.0,2.0
226,Rock,0.5,0.5,2.0,1.0,2.0,1.0,2.0,0.5,2.0,0.5,1.0,1.0,1.0,1.0,1.0,1.0,2.0,1.0
241,Ghost,0.0,1.0,1.0,1.0,1.0,1.0,0.0,0.5,0.0,1.0,1.0,0.5,1.0,2.0,1.0,2.0,1.0,1.0
740,Flying,1.0,1.0,1.0,2.0,0.5,2.0,0.5,1.0,0.0,1.0,1.0,0.5,2.0,1.0,1.0,1.0,1.0,1.0

In [16]:
# Final Dataframe for Pokemon Main
pokimain_df.head()

,pokedex_number,name,generation,status,species,type_number,type_1,type_2,height_m,weight_kg,...,against_flying,against_psychic,against_bug,against_rock,against_ghost,against_dragon,against_dark,against_steel,against_fairy,is_starter
0,1,Bulbasaur,1,Normal,Seed Pokémon,2,Grass,Poison,0.7,6.9,...,2.0,2.0,1.0,1.0,1.0,1.0,1.0,1.0,0.5,1.0
1,2,Ivysaur,1,Normal,Seed Pokémon,2,Grass,Poison,1.0,13.0,...,2.0,2.0,1.0,1.0,1.0,1.0,1.0,1.0,0.5,1.0
2,3,Venusaur,1,Normal,Seed Pokémon,2,Grass,Poison,2.0,100.0,...,2.0,2.0,1.0,1.0,1.0,1.0,1.0,1.0,0.5,1.0
3,3,Mega Venusaur,1,Normal,Seed Pokémon,2,Grass,Poison,2.4,155.5,...,2.0,2.0,1.0,1.0,1.0,1.0,1.0,1.0,0.5,0.0
4,4,Charmander,1,Normal,Lizard Pokémon,1,Fire,NaN,0.6,8.5,...,1.0,1.0,0.5,2.0,1.0,1.0,1.0,0.5,0.5,1.0

In [17]:
# Final Dataframe for Pokemon Starters
starter_cleandf.head()

,pokedex_number,name,generation,is_starter,total_points,hp,attack,defense,sp_attack,sp_defense,speed
0,1,Bulbasaur,1,1.0,318,45,49,49,65,65,45
1,2,Ivysaur,1,1.0,405,60,62,63,80,80,60
2,3,Venusaur,1,1.0,525,80,82,83,100,100,80
4,4,Charmander,1,1.0,309,39,52,43,60,50,65
5,5,Charmeleon,1,1.0,405,58,64,58,80,65,80

In [18]:
# Final Dataframe for Pokemon Types
effectiveness_df.head()

,type_1,against_normal,against_fire,against_water,against_electric,against_grass,against_ice,against_fight,against_poison,against_ground,against_flying,against_psychic,against_bug,against_rock,against_ghost,against_dragon,against_dark,against_steel,against_fairy
4,Fire,1.0,0.5,2.0,1.0,0.5,0.5,1.0,1.0,2.0,1.0,1.0,0.5,2.0,1.0,1.0,1.0,0.5,0.5
9,Water,1.0,0.5,0.5,2.0,2.0,0.5,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,0.5,1.0
13,Bug,1.0,2.0,1.0,1.0,0.5,1.0,0.5,1.0,0.5,2.0,1.0,1.0,2.0,1.0,1.0,1.0,1.0,1.0
24,Normal,1.0,1.0,1.0,1.0,1.0,1.0,2.0,1.0,1.0,1.0,1.0,1.0,1.0,0.0,1.0,1.0,1.0,1.0
30,Poison,1.0,1.0,1.0,1.0,0.5,1.0,0.5,0.5,2.0,1.0,2.0,0.5,1.0,1.0,1.0,1.0,1.0,0.5

In [19]:
# Final Dataframe for Pokemon Legndaries
legendary_cleandf.head()

,pokedex_number,name,is_sub_legendary,is_legendary,is_mythical,total_points,hp,attack,defense,sp_attack,sp_defense,speed
182,144,Articuno,1,0,0,580.0,90.0,85.0,100.0,95.0,125.0,85.0
183,145,Zapdos,1,0,0,580.0,90.0,90.0,85.0,125.0,90.0,100.0
184,146,Moltres,1,0,0,580.0,90.0,100.0,90.0,125.0,85.0,90.0
188,150,Mewtwo,0,1,0,680.0,106.0,110.0,90.0,154.0,90.0,130.0
189,150,Mega Mewtwo X,0,1,0,780.0,106.0,190.0,100.0,154.0,100.0,130.0

In [23]:
# Connection to PostgreSQL server
rds_connection_string = "postgres:postgres@localhost:5432/pokemon.db"
engine = create_engine(f"postgresql://{rds_connection_string}")

In [24]:
engine.table_names()

[]

In [27]:
# Dataframes to tables in PostgresSQL
pokimain_df.to_sql(name='pokemon_data', con=engine, if_exists='append', index=False)
starter_cleandf.to_sql(name='starter_data', con=engine, if_exists='append', index=False)
legendary_cleandf.to_sql(name='legendary_data', con=engine, if_exists='append', index=False)
effectiveness_df.to_sql(name='type_data', con=engine, if_exists='append', index=False)

In [26]:
engine.table_names()

['pokemon_data', 'starter_data', 'legendary_data', 'type_data']